# Generated by Django 6.0.5 on 2026-05-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Текст ответа")),
                ("is_correct", models.BooleanField(default=False, verbose_name="Правильный ответ")),
                ("explanation", models.TextField(blank=True, verbose_name="Пояснение к ответу")),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название курса")),
                (
                    "description",
                    models.TextField(help_text="Подробное описание курса", verbose_name="Описание"),
                ),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликован")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название урока")),
                ("content", models.TextField(help_text="Текст урока", verbose_name="Содержание")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="Ссылка на видео"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Одиночный выбор"),
                            ("multiple", "Множественный выбор"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["test", "order"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название теста")),
                ("description", models.TextField(blank=True, verbose_name="Описание теста")),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=70,
                        help_text="Минимальный процент правильных ответов для прохождения",
                        verbose_name="Проходной балл (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.CreateModel(
            name="UserTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score", models.FloatField(verbose_name="Результат (%)")),
                (
                    "correct_answers",
                    models.PositiveIntegerField(default=0, verbose_name="Правильных ответов"),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(default=0, verbose_name="Всего вопросов"),
                ),
                ("is_passed", models.BooleanField(default=False, verbose_name="Тест пройден")),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время завершения"),
                ),
            ],
            options={
                "verbose_name": "Результат теста",
                "verbose_name_plural": "Результаты тестов",
                "ordering": ["-completed_at"],
            },
        ),
    ]
